import type { Metadata } from "next";
import { Provider } from "@/components/provider/Provider";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <Provider >
        {children}
        </Provider>
      </body>
    </html>
  );
}
